# 4.4 Excercises
print("\n")
print ("You're never gonna make it \nThere's no way that you make it \nYeah maybe you can fake it \nBut you're never gonna make it")
print("\n")
print (" A moment of pain is worth a lifetime of glory. ") #Pete said that from the movie Unbroken
print("\n")
print("A string in Python is a sequence of characters, that once defined cannot be changed.")
print("\n")
print("A integer in Pyhton is a postive, negitive whole number, or xero, without a decimal point.")
print("\n")
print("A float in Python is a number with a decimal point.") #Question 5
print ("\n")
print (543/3)
print ("\n")
print (int(543/3))
print ("\n")
print (543%3)
print ("\n")
print (1000%9)
print ("\n")
print (int(434/10)) #Question 10
print ("\n")
print (3%2)
print ("\n")
print (5%5)
print ("\n")
print (555/2)
print ("\n")
print (123/2)
print ("\n")
print (123//2) #Question 15
print ("\n")
print (123%2)
print ("\n")
print (764%2)
print ("\n")
print (165//2)
print ("\n")
print (1.2+1.3)
print ("\n")
print (5+5) #Question 20
print ("\n")
print (2.5-10)
print ("\n")
print (5-10.5)
print ("\n")
print (10/2)
print ("\n")
print (10*2.5)
print ("\n")
print (5*10) #Question 25
print ("\n")
print ("Finn Abey, "* 10)
print ("\n")
print ("Finn Abey\n"* 10)
print ("\n")
print ("5+10=" + str(5+10))
print ("\n")
print ("15/2=" + str(2+5.5))
print ("\n")
print ("30/2*5=" + str(25.0+50.0)) #Question 30
print ("\n")
print ("30/2*5=" + str(25+50))
print ("\n")
