#first program
print("hello world")
print("Finn")
print("Kris White")
print ("King's High School")
print("My age is 15 almost 16")
print ("I have 200 hours on my favourite video game")
print(2022+25)
print(15+100)
print(658/7)
print (2022-1969)
print ("Minecraft and Brawl Stars")
print ("Economics")
print ('king\'s high school')
print("Top\nBottom")
print("44+66")